### ISSUE TITLE
ziomon/ziomon_fcpconf: Compilation errors

### ISSUE THREAD

**Issue by Obirvalger** [ibm-s390-tools/s390-tools#17]
Hi, when I try to run ziomon/ziomon_fcpconf I get following errors:
`Global symbol "$map_dev" requires explicit package name (did you forget to declare "my $map_dev"?) at ziomon/ziomon_fcpconf line 61.
Global symbol "$map_dev" requires explicit package name (did you forget to declare "my $map_dev"?) at ziomon/ziomon_fcpconf line 65.
Unmatched right curly bracket at ziomon/ziomon_fcpconf line 67, at end of line
syntax error at ziomon/ziomon_fcpconf line 67, near "}"
Execution of ziomon/ziomon_fcpconf aborted due to compilation errors.`

Probably some cycle was disappeared from line 60.

**Comment by michael-holzheu** [comment]
Your are right. During the GPL->MIT conversion process from 1.39.0 to 2.0.0 obviously one line has been lost.
The following patch fixes the problem:

```c
diff --git a/ziomon/ziomon_fcpconf b/ziomon/ziomon_fcpconf
index 7643540..c51690e 100644
--- a/ziomon/ziomon_fcpconf
+++ b/ziomon/ziomon_fcpconf
@@ -58,6 +58,7 @@ sub store_mapper_devices
        my $src_dir = shift();
        my @entries = grep { ! /^\./ } dir_content($src_dir);
 
+       foreach my $map_dev (@entries) {
                my $tf = catfile($src_dir, "$map_dev");
                my $mm = `stat -L -c%t:%T $tf`;
                chomp($mm);
```
