### ISSUE TITLE
Output of lscss is confusing with vfio-ccw devices

### ISSUE THREAD

**Issue by cohuck** [ibm-s390-tools/s390-tools#32]
Setup: LPAR with one subchannel for a dasd reassigned from the I/O subchannel driver to the vfio-ccw driver (no mdev created yet)

`lscss` shows
```
Device   Subchan.  DevType CU Type Use  PIM PAM POM  CHPIDs           
----------------------------------------------------------------------
0.0.0900 0.0.001f  1732/01 1731/01 yes  80  80  ff   15000000 00000000
0.0.0901 0.0.0020  1732/01 1731/01 yes  80  80  ff   15000000 00000000
0.0.0902 0.0.0021  1732/01 1731/01 yes  80  80  ff   15000000 00000000
0.0.2a01 0.0.021d  3390/0e 3990/e9 yes  f0  f0  ff   19293909 00000000
0.0.2b01 0.0.031d  3390/0e 3990/e9 yes  f0  f0  ff   1a2a3a0a 00000000
0.0.2b08 0.0.0324  3390/0e 3990/e9 yes  f0  f0  ff   1a2a3a0a 00000000
none     0.0.0325                       f0  f0  ff   1a2a3a0a 00000000
0.0.2c01 0.0.041d  3390/0e 3990/e9 yes  f0  f0  ff   0a1a2838 00000000
0.0.2d01 0.0.049d  3390/0e 3990/e9 yes  f0  f0  ff   09192939 00000000
```
The line for subchannel 0.0.0325 is a bit confusing, as it looks like there is something wrong with the subchannel (previously, I saw output like that only if there was some problem with device recognition in the common I/O layer, as the I/O subchannel driver always registers a ccw device.) `lscss --all` does not reveal anything, either.

The subchannel shows up correctly with `lscss --vfio`.
```
MDEV                                  Subchan.  PIM PAM POM  CHPIDs           
------------------------------------------------------------------------------
none                                  0.0.0325  f0  f0  ff   1a2a3a0a 00000000
```
I'm not sure what the best approach is here. If lscss only showed devices bound to a subchannel driver, we would miss chsc or eadm subchannels if the driver is not present. (I think we can rely on the I/O subchannel driver always being present.)

I would, however, expect the output of `lscss --all` to include the output of `lscss --vfio`. Or maybe a new option `lscss --everything` or so.

**Comment by cohuck** [comment]
OK, that sounds like we have to live with 'lscss handling of vfio-ccw devices is a bit odd'.

But can we get an update for the man page? It currently states
```
NOTES
       In rare situations a device might temporarily not be accessible to  the
       subchannel.  Then  "none" is displayed as the device identifier and the
       other device attributes are empty.
```
That is not really true for vfio-ccw devices.

**Comment by sebott** [comment]
Good point. I'll add something like:
`For subchannels bound to an alternate driver (most notably vfio_ccw) the device identifier can also be displayed as "none". In this case use the --vfio option to show VFIO specific subchannel information.`

**Comment by cohuck** [comment]
Possibly s/can/may/ or s/can/will/ ? Otherwise, sounds good to me.
