### ISSUE TITLE
fdasd: Check for partitions performed too early ? 

### ISSUE THREAD

**Issue by schwefel** [ibm-s390-tools/s390-tools#4]
Hi,
I'm running fdasd with the -f option specified to loop devices. While this works fine w /dev/loop0, it fails for /dev/loop1 with
```
   fdasd error:  device verification failed 
   Partition '/dev/loop1' (7/1) detected where device is required
```
Turns out, that the current code does call 
`static void fdasd_verify_device(fdasd_anchor_t *anc, char *name)`
way before the options passed to fdasd invocation are evaluated and then check
`if (minor(dst.st_rdev) & PARTN_MASK)`
does prevent fdasd to work on devices w 'minor number mod 4 != 0'.
Any chance, that we could fdasd get changed, to skip the call to fdasd_verify_device or some of the checks in there, depending on the -f option set or not ?

**Comment by michael-holzheu** [comment]
@hoeppnerj : Could you please have a look?

**Comment by michael-holzheu** [comment]
@schwefel : Could you please also describe the setup how you create the loop devices?

**Comment by schwefel** [comment]
Sure, sorry, I missed this. Here are the commands, to repro the scenario:
`dd if=/dev/zero of=loopfile bs=4096 count=4096
losetup -P /dev/loop1 loopfile
fdasd -f -r  /dev/loop1`

**Comment by hoeppnerj** [comment]
Hi, this issue was fixed internally by skipping the partition check when the force option is specified.
The fix will be available here on github with the next sync.
