### ISSUE TITLE
lsqeth crashes if the qeth module is not loaded

### ISSUE THREAD

**Issue by cohuck** [ibm-s390-tools/s390-tools#43]
Running 'lsqeth' if the qeth driver is not loaded gives you:

>  free(): invalid pointer

and the core is dumped.

This code in main() (lsqeth.c) where it apparently crashes looks fishy:
```
                path = util_path_sysfs("bus/ccwgroup/drivers/qeth/");
                count = util_scandir(&de_vec, alphasort, path, "%s",
                                     ID_FORMAT);
                free(path);
                for (i = 0; i < count; i++) {
                        /* Check if a symbolic link */
                        if (de_vec[i]->d_type != DT_LNK)
                                continue;
                        if (i > 0)
                                rec = setup_rec();
                        print_device(rec, de_vec[i]->d_name);
                        free(rec);
                }
                util_scandir_free(de_vec, count);
```
If the qeth module is not loaded, /sys/bus/ccwgroup/drivers/qeth/ will not exist. Consequently, __scandir() when called by util_scandir()->scandir_regexp() will fail to open it and return -1 (even though the documentation states that util_scandir() returns a 'Number of returned directory entries', which seems to imply >= 0 to me). The code above does not seem to be prepared for handling count == -1.

Not sure where the best place to fix that is.

**Comment by hoeppnerj** [comment]
fyi, the just pushed fix addresses only the behaviour of [util_ptr_vec_free()](https://github.com/ibm-s390-tools/s390-tools/blob/master/include/lib/util_base.h#L41). I found numerous places in other tools that don't check for the util_scandir() return value as well. This will be addressed in another patch series.

Thanks for reporting!
