### ISSUE TITLE
zkey cryptsetup -r asks passphrase three time interactively, should support keyfile

### ISSUE THREAD

**Issue by xnox** [ibm-s390-tools/s390-tools#58]
I'm using luks2, and when running `zkey cryptsetup -r` it asks the passphrase three time (twice by cryptsetup, and once by zkey-cryptsetup).

Normally, when using cryptsetup one can specify a keyfile with a passphrase as the second options, or as a keyarg option `--key-file`

It would be nice if one could pass `--key-file /run/path/to/passphrase-file` to `zkey cryptsetup` command which would then in turn pass that to `cryptsetup` and `zkey-cryptsetup` commands.

But also zkey-cryptsetup needs to grow the `--key-file` option.

BTW this is _not_ about master keyfile option....

This is needed for automation / UI driven zkey setup.

**Comment by ifranzki** [comment]
Good idea. Will take that into consideration.....

BTW: zkey-cryptsetup already has a --key-file option (together with --keyfile-offset and --keyfile-size) that behaves just like the equivalent options of cryptsetup.
