### ISSUE TITLE
BOOT_IMAGE not set for /proc/cmdline

### ISSUE THREAD

**Issue by sharkcz** [ibm-s390-tools/s390-tools#67]
When using recent zipl for booting an up-to-date Fedora Rawhide system (uses BLS boot entries), I don't see the BOOT_IMAGE variable being set by the bootloader, so it doesn't appear in /proc/cmdline. We get the same behaviour with RHEL-8.1 (work in progress, see bug [1728677](https://bugzilla.redhat.com/show_bug.cgi?id=1728677)) so I suspect the secure boot patches might break it. Looking further ...

**Comment by stefan-haberland** [comment]
Where did you IPL from? DASD or SCSI? Was secure boot enabled?

**Comment by sharkcz** [comment]
DASD in z/VM guest, secureboot not used

**Comment by stefan-haberland** [comment]
Thanks, I will have a look.

**Comment by stefan-haberland** [comment]
Looks like stage 2 overwrites the extra_param when loading the stage 3 parameter page. I need to shuffle around the memory area used there.
