### ISSUE TITLE
zfcpdump README is out of date

### ISSUE THREAD

**Issue by xnox** [ibm-s390-tools/s390-tools#89]
I think the zfcpdump code now expects for kernel image to be at `/lib/s390-tools/zfcpdump/zfcpdump-image`, yet https://github.com/ibm-s390-tools/s390-tools/blob/master/zfcpdump/README.part#L34 mentions the previous name of `/lib/s390-tools/zfcpdump/zfcpdump_part.image`

Please fix the docs to match the current code.

**Comment by hoeppnerj** [comment]
Correct, it should read `zfcpdump-image`. Will be fixed internally and pushed soon.
